{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

with lib;
{
  imports = [
    inputs.niri.homeModules.niri
    inputs.dms.homeModules.dank-material-shell
    inputs.dms.homeModules.niri
    inputs."dms-plugin-registry".modules.default
  ];

  xdg.configFile."niri/dms/binds.kdl".text = ''
    binds {
        Ctrl+Space hotkey-overlay-title="Application Launcher" { spawn "dms" "ipc" "call" "spotlight" "toggle"; }

        Mod+Shift+Slash { show-hotkey-overlay; }

        Mod+O repeat=false { toggle-overview; }
        Mod+Q repeat=false { close-window; }

        Mod+Left  { focus-column-left; }
        Mod+Right { focus-column-right; }
        Mod+H     { focus-column-left; }
        Mod+L     { focus-column-right; }

        Mod+F { maximize-column; }
        Mod+Shift+F { fullscreen-window; }

        Mod+V { toggle-window-floating; }
        Mod+Shift+V { switch-focus-between-floating-and-tiling; }

        Mod+WheelScrollDown cooldown-ms=150 { focus-column-right; }
        Mod+WheelScrollUp   cooldown-ms=150 { focus-column-left; }

        Mod+Ctrl+WheelScrollDown cooldown-ms=150 { focus-workspace-down; }
        Mod+Ctrl+WheelScrollUp   cooldown-ms=150 { focus-workspace-up; }

        Print      { screenshot; }
        Ctrl+Print { screenshot-screen; }
        Alt+Print  { screenshot-window; }
    }
  '';

  # Home Manager's checkLinkTargets can fail when a managed target is a directory
  # and already exists (cmp errors on directories). Force replacement.
  xdg.configFile."DankMaterialShell/plugins/dankGifSearch".force = true;

  xdg.configFile."DankMaterialShell/plugins/volumeMixer" = {
    # Dev-friendly: keep this plugin as a live symlink to your dotfiles checkout
    # so `dms ipc call plugins reload volumeMixer` picks up changes instantly.
    source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.config/nixos-dotfiles/modules/desktops/niri/dms-plugins/volumeMixer";
    recursive = true;
    force = true;
  };

  home.packages = with pkgs; [
    kdePackages."kdeconnect-kde"
  ];

  # Cursor: prefer declarative control via niri-flake/Home Manager.
  # DMS' settings UI doesn't reliably apply cursor changes live.
  programs.niri.settings.cursor = {
    theme = "Adwaita";
    size = 16;
  };

  # Enable Num Lock by default (niri input.keyboard.numlock).
  programs.niri.settings.input.keyboard.numlock = mkDefault true;

  # Focus follows mouse (hover-to-focus).
  programs.niri.settings.input.focus-follows-mouse.enable = mkDefault true;

  # Disable mouse acceleration.
  programs.niri.settings.input.mouse.accel-profile = mkDefault "flat";

  home.pointerCursor = {
    gtk.enable = true;
    package = pkgs.adwaita-icon-theme;
    name = "Adwaita";
    size = 16;
  };

  # Some upstream modules (e.g. DMS niri includes) expect this path to be a set.
  # If `border` is left as `null`, evaluation fails when selecting `.enable`.
  programs.niri.settings.layout.border.enable = mkDefault false;

  programs.dank-material-shell = {
    enable = true;

    # DMS plugins (from the registry flake). Enable by plugin ID, e.g.
    # plugins.dankBatteryAlerts.enable = true;
    # plugins.mediaPlayer = { enable = true; settings.preferredSource = "spotify"; };
    plugins = {
      dankGifSearch.enable = true;
      dockerManager.enable = true;
      dankKDEConnect.enable = true;
      dankStickerSearch.enable = true;
      developerUtilities.enable = true;
      dankLauncherKeys.enable = true;
      powerOptions.enable = true;
    };

    niri.includes = {
      enable = true;             # Enable config includes hack. Enabled by default.
      override = true;           # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
      originalFileName = "hm";   # A new name (without extension) for the config file generated by niri-flake.
      filesToInclude = [         # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
        "alttab"                 # Please note that niri will throw an error if any of these files are missing.
        "binds"
        "colors"
        "layout"
        "outputs"
        "wpblur"
      ];
    };
  };
}
